### ISSUE TITLE
Edit profile in the FE - necessary password prompt

### ISSUE THREAD

**Issue by Gorli** [franzholz/agency#1]
Hello Franz!

My environment: TYPO3 7.6.10, div2007, Agency 0.3.1 - recently, I also use Agency

When editing a user profile in the FE, it is necessary to enter the password again. But according to label and I believe that it is necessary only on request. Is it possible that another request to stop

regards

Gorli

**Comment by franzholz** [comment]
duplicate to
https://forge.typo3.org/issues/77211
