### ISSUE TITLE
PHP Runtime Deprecation Notice: Non-static method tx_div2007_alpha::wrapInBaseClass_fh001()

### ISSUE THREAD

**Issue by Gorli** [franzholz/agency#3]
Hello Franz,

New error:
#1: PHP Runtime Deprecation Notice: Non-static method tx_div2007_alpha::wrapInBaseClass_fh001() should not be called statically, assuming $this from incompatible context in ...\typo3conf\ext\agency\control\class.tx_agency_control_main.php line 120 (More information)

**Comment by franzholz** [comment]
duplicate to
https://forge.typo3.org/issues/77232
